- commands/channel.go
> Add the channel search command

- README.md
- commands/auth.go
> Remove --username parameter from the access tokens docs

- commands/auth.go
> Checks that the access-token is valid and errors if it's not

- commands/ldap.go
- go.mod
- go.sum
Adds the `ldap` command with the `sync` subcommand.
> [MM-19059] Adds ldap command

- commands/command.go
Adds the `command` subcommand, porting the features that are accessible through the API.
> [MM-19057] Adds the command subcommand

- README.md
As the project is now managed in JIRA, this PR removes the roadmap section from the README file.
> Removes the roadmap from the README

- README.md
I think it's good idea - add badge for Go Report
> Update README - adds GoReport badge

- commands/config.go
Adds the config command with the `show` and `get` subcommands.
> [MM-19058] Add config command

- commands/channel_test.go
Adds tests for the `mmctl channel search` command.
> Add tests for the search channel command

- commands/user_test.go
Unit tests added for UserCreateCmd
Fixes [mattermost/mattermost-server#13048](https://github.com/mattermost/mattermost-server/issues/13048)
> [MM-20032] Unit testing added for UserCreateCmd

- go.mod
- go.sum
See https://community-release.mattermost.com/core/pl/9ysybypeo7y5jcr1x9m4fch5te
> Remove go modules workaround

- commands/command_test.go
Add unit test for commandListCmd 
fixes : https://github.com/mattermost/mattermost-server/issues/13112
> [GH-13112] Add unit tests to "CommandListCmd" to use testify

- .circleci/config.yml
- Makefile
- README.md
- commands/mmctl_e2e_test.go
- commands/mmctl_test.go
- commands/mmctl_unit_test.go
- commands/mmctltestlib.go
- commands/plugin_test.go
- commands/user_e2e_test.go
- magefile.go
This PR adds an example of an end to end test and the necessary infrastructure for the CI.
> [MM-19912] Add end to end tests to mmctl

- commands/license_test.go
> fix model import on licence test file for testing

- commands/user.go
Removes a bad example for the update user email command
> Remove bad update user email example

- commands/group_test.go
Add unit tests to the "TeamGroupListCmd" mmctl command
JIRA:  https://mattermost.atlassian.net/browse/MM-21241
Fixes https://github.com/mattermost/mattermost-server/issues/13398
> Add unit tests to the "TeamGroupListCmd" mmctl command

- commands/team_test.go
Add unit tests to the "ListTeamsCmd" mmctl command
Fixes https://github.com/mattermost/mattermost-server/issues/13465
> [GH13465] Add unit tests to the "ListTeamsCmd" mmctl command

- commands/team_test.go
Add unit tests to the "AddUsersCmd" mmctl command
JIRA: https://mattermost.atlassian.net/browse/MM-21242
Fixes https://github.com/mattermost/mattermost-server/issues/13397
> Add unit tests to the "AddUsersCmd" mmctl command

- commands/group_test.go
- docs/mmctl_user_email.md
Added unit tests for checking team group status command
Fixes : https://github.com/mattermost/mattermost-server/issues/13399
Jira : https://mattermost.atlassian.net/browse/MM-21240
> Fixes #13399 : Add unit tests to the "TeamGroupStatusCmd" mmctl command

- commands/plugin.go
- commands/plugin_test.go
Add unit tests to "PluginDeleteCmd" to use testify
Fixes https://github.com/mattermost/mattermost-server/issues/13121
> [GH13121] Add unit tests to "PluginDeleteCmd" to use testify

- commands/channel.go
- commands/channel_test.go
- docs/mmctl_user_email.md
Added unit tests for list channels command
Fixes : https://github.com/mattermost/mattermost-server/issues/13458
Jira : https://mattermost.atlassian.net/browse/MM-21387
> Fixes #13458 : Add unit tests to the "ListChannelsCmd" mmctl command

- commands/group_test.go
Added unit tests for `TestChannelGroupListCmd`
Fixes https://github.com/mattermost/mattermost-server/issues/13400
> [GH-13400] Add unit test for TestChannelGroupListCmd

- commands/command.go
- commands/command_test.go
- docs/mmctl_command.md
- docs/mmctl_command_archive.md
- docs/mmctl_command_list.md
This PR fixes some issues that @wiggin77 arise from a [previous PR](https://github.com/mattermost/mmctl/pull/102#pullrequestreview-345540684)
https://mattermost.atlassian.net/browse/MM-19200
> Some changes suggested to improve consistency

- commands/channel.go
- commands/channel_test.go
Unit tests for the AddChannelUsersCmd have been added.
Fixes https://github.com/mattermost/mattermost-server/issues/13460
> GH-13460: Add unit tests for AddChannelUsersCmd mmctl command.

- commands/init.go
https://mattermost.atlassian.net/browse/MM-22167
> [MM-22167] Add custom User-Agent to mmctl's requests

- commands/channel.go
- commands/channel_test.go
Continued work of proposal in #62
> commands/channel: use formatted string on errors

- commands/version.go
> Bump mmctl version to 5.26

- commands/auth.go
- commands/auth_e2e_test.go
- commands/mmctltestlib.go
- Trim trailing slashes from server url
- https://mattermost.atlassian.net/browse/MM-24448
> MM-24448: trim trailing slash from url

- .circleci/config.yml
> Bump golang build image

- .circleci/config.yml
Adding support for draft pre-releases
https://mattermost.atlassian.net/browse/MM-28204
> Publish master

- client/client.go
- commands/system.go
- commands/system_test.go
- docs/mmctl_system.rst
- docs/mmctl_system_status.rst
- docs/mmctl_system_version.rst
- mocks/client_mock.go
https://mattermost.atlassian.net/browse/MM-29193
> [MM-29193] Add system status command

- Makefile
Added `PHONY` for all make targets.
Fixes https://github.com/mattermost/mmctl/issues/136
> added PHONY for all make targets

- commands/team_e2e_test.go
Add end to end tests to the renameTeamCmdF mmctl command
Fixes https://github.com/mattermost/mattermost-server/issues/15674
> Add end to end tests to the renameTeamCmdF mmctl command

- commands/team_users_e2e_test.go
Adds end-to-end tests for `teamUsersRemoveCmdF`.
Fixes https://github.com/mattermost/mattermost-server/issues/15678
> [MM-29172] Add E2E tests for teamUsersRemoveCmdF

- commands/channel_users_e2e_test.go
**Summary**
Adds e2e tests for channelUsersAddCmdF.
**Ticket Link**
Fixes mattermost/mattermost-server#15814
JIRA: https://mattermost.atlassian.net/browse/MM-29336
> [MM-29336] Add e2e tests to channelUsersAddCmdF

- commands/channel_e2e_test.go
Close https://github.com/mattermost/mattermost-server/issues/15811
> Add e2e tests for searchChannelCmdF

- commands/team_e2e_test.go
Adds e2e tests for `createTeamCmdF`.
Fixes https://github.com/mattermost/mattermost-server/issues/15670
JIRA: https://mattermost.atlassian.net/browse/MM-29164
> [MM-29164] Add e2e tests to createTeamCmdF

- commands/team_e2e_test.go
Add end to end tests to listTeamsCmdF.
Fixes https://github.com/mattermost/mattermost-server/issues/15672
JIRA: https://mattermost.atlassian.net/browse/MM-29166
> [MM-29166] Add e2e tests to listTeamsCmdF

- commands/plugin_marketplace_e2e_test.go
Added e2e test for pluginMarketplaceInstallCmdF. 
Fixes: mattermost/mattermost-server#15944
JIRA: https://mattermost.atlassian.net/browse/MM-29566
> [MM-29566] Add e2e test for pluginMarketplaceInstallCmdF

- .circleci/config.yml
- .gitlab-ci.yml
> Partial revert. Bring back circleci for the time being. 

- client/client.go
- commands/user.go
- commands/user_e2e_test.go
- commands/user_test.go
- docs/mmctl_user_list.rst
- mocks/client_mock.go
Fixes mattermost/mattermost-server#15686
> Add team flag to get user list of a given team

- Makefile
Increases the timeout of the tests to avoid CI failures
https://mattermost.atlassian.net/browse/MM-30264
> [MM-30264] Increase test timeout

- commands/bot_e2e_test.go
Add e2e tests to `mmctl bot list` command.
Fixes: https://github.com/mattermost/mattermost-server/issues/16002
JIRA: https://mattermost.atlassian.net/browse/MM-29806
> [MM-29806] Add end-2-end tests to bot list command

- commands/command_e2e_test.go
Add end to end tests to the "modifyCommandCmdF"
Fixes mattermost/mattermost-server#15941
[jira](https://mattermost.atlassian.net/browse/MM-29563)
> MM-29563 added e2e tests to "modifyCommandCmdF"

- .gitlab-ci.yml
> Use own registry images

- commands/bot_e2e_test.go
Add e2e tests to `mmctl bot assign` command.
Fixes: https://github.com/mattermost/mattermost-server/issues/16005
JIRA: https://mattermost.atlassian.net/browse/MM-29809
> [MM-29809] Add end-2-end tests to bot assign command

- commands/logs_e2e_test.go
Add end to end tests to "logsCmdF"
Fixes mattermost/mattermost-server#16006
jira: [MM-29810](https://mattermost.atlassian.net/browse/MM-29810)
> MM-29810 added e2e tests to "logsCmdF"

- .gitlab-ci.yml
> Remove runner tag

- .circleci/config.yml
- .gitlab-ci.yml
- Makefile
Add e2e tests to coverage.
https://mattermost.atlassian.net/browse/MM-30267
> [MM-30267] add e2e tests to coverage

- commands/group_e2e_test.go
commands/group: add e2e test for ChannelGroupDisableCmd
https://mattermost.atlassian.net/browse/MM-30224
> [MM-30224] commands/group: add e2e test for ChannelGroupDisableCmd

- .gitlab-ci.yml
> Use newer golangci-lint version

- commands/config.go
- commands/config_e2e_test.go
Add e2e test case for configEditCmd
https://mattermost.atlassian.net/browse/MM-29733
Fixes https://github.com/mattermost/mattermost-server/issues/15981
> [MM-29733] Add e2e test case for configEditCmd

- commands/import.go
- docs/mmctl_import_job_show.rst
- docs/mmctl_import_list.rst
Some minor updates to the `import` command documentation as requested by the technical writers team.
> Update import command documentation

- commands/plugin_marketplace_e2e_test.go
Let's check the plugin version from the marketplace first 😅 (This was causing inc PRs to fail)
> commands/plugin_marketplace_e2e_test: fix plugin version

- commands/export_e2e_test.go
Adds test ids for export command e2e tests
> Adds export e2e test ids

- commands/channel.go
- commands/user.go
- docs/mmctl_channel_make_private.rst
- docs/mmctl_channel_modify.rst
- docs/mmctl_user_convert.rst
- docs/mmctl_user_email.rst
- docs/mmctl_user_resetmfa.rst
- docs/mmctl_user_verify.rst
This PR reflects the changes added to the product docs in https://github.com/mattermost/docs/pull/4360
> Add documentation changes to reflect those in the product docs

- commands/roles.go
- commands/roles_test.go
Display user roles on update.
https://mattermost.atlassian.net/browse/MM-32395
> feat(commands): added displaying user roles on update

- commands/ldap.go
- docs/mmctl_ldap_idmigrate.rst
Update the `idmigrate` docs to reflect the improvements made in https://github.com/mattermost/docs/pull/4788
The PR is marked as a draft until the docs one gets merged to ensure both are synced
> Update idmigrate docs

- .gitlab-ci.yml
Needed to update the image tag.
> Build on 1.17.0 for https://github.com/mattermost/mmctl/pull/381

- .circleci/config.yml
- .gitlab-ci.yml
> Use consistent image

- .circleci/config.yml
- .gitlab-ci.yml
- commands/main_test.go
- commands/mmctl_e2e_test.go
- commands/mmctl_unit_test.go
- commands/utils_unix.go
- magefile.go
> Homebrew fixes release 5.38

- commands/init.go
Fixes a small merge error occurred while merging #377
> Fix a merge error of #377

- commands/user_e2e_test.go
Add e2e test for `migrateAuthCmdF`
https://mattermost.atlassian.net/browse/MM-31418
> [MM-31418] commands/user: add migrate auth e2e tests

- commands/version.go
- go.mod
- go.sum
- vendor/github.com/mattermost/mattermost-server/v6/api4/config.go
- vendor/github.com/mattermost/mattermost-server/v6/api4/config_local.go
- vendor/github.com/mattermost/mattermost-server/v6/app/notification.go
- vendor/github.com/mattermost/mattermost-server/v6/app/oauth.go
- vendor/github.com/mattermost/mattermost-server/v6/app/post.go
- vendor/github.com/mattermost/mattermost-server/v6/config/diff.go
- vendor/github.com/mattermost/mattermost-server/v6/model/config.go
- vendor/github.com/mattermost/mattermost-server/v6/model/version.go
- vendor/modules.txt
update mmctl to the next path release
> update mmctl to 6.0.4

- commands/version.go
- go.mod
- go.sum
- vendor/github.com/mattermost/mattermost-server/v5/app/file.go
- vendor/modules.txt
> update mmctl to 5.37.7

- commands/version.go
- go.mod
- go.sum
- vendor/github.com/mattermost/mattermost-server/v6/api4/post.go
- vendor/github.com/mattermost/mattermost-server/v6/app/app_iface.go
- vendor/github.com/mattermost/mattermost-server/v6/app/opentracing/opentracing_layer.go
- vendor/github.com/mattermost/mattermost-server/v6/app/plugin.go
- vendor/github.com/mattermost/mattermost-server/v6/app/post.go
- vendor/github.com/mattermost/mattermost-server/v6/app/post_metadata.go
- vendor/github.com/mattermost/mattermost-server/v6/jobs/resend_invitation_email/worker.go
- vendor/github.com/mattermost/mattermost-server/v6/model/client4.go
- vendor/github.com/mattermost/mattermost-server/v6/model/feature_flags.go
- vendor/github.com/mattermost/mattermost-server/v6/model/license.go
- vendor/github.com/mattermost/mattermost-server/v6/model/version.go
- vendor/github.com/mattermost/mattermost-server/v6/store/sqlstore/post_store.go
- vendor/github.com/mattermost/mattermost-server/v6/store/sqlstore/store.go
- vendor/github.com/mattermost/mattermost-server/v6/store/sqlstore/upgrade.go
- vendor/github.com/mattermost/mattermost-server/v6/utils/license.go
- vendor/github.com/mattermost/mattermost-server/v6/web/handlers.go
- vendor/modules.txt
> update mmctl to 6.3.0

- .circleci/config.yml
> Lock CI from /release-6.4

- .github/workflows/build.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/test.yml
update ci to run on release branches as well
> update ci to run on release branches as well

- commands/version.go
- go.mod
- go.sum
- vendor/github.com/mattermost/mattermost-server/v6/api4/team.go
- vendor/github.com/mattermost/mattermost-server/v6/app/channel.go
- vendor/github.com/mattermost/mattermost-server/v6/model/config.go
- vendor/github.com/mattermost/mattermost-server/v6/model/version.go
- vendor/github.com/mattermost/mattermost-server/v6/services/docextractor/documents.go
- vendor/github.com/mattermost/mattermost-server/v6/store/sqlstore/upgrade.go
- vendor/github.com/mattermost/mattermost-server/v6/web/handlers.go
- vendor/github.com/mattermost/mattermost-server/v6/web/saml.go
- vendor/modules.txt
https://mattermost.atlassian.net/browse/DOPS-776
> update mmctl to 6.2.3

- commands/version.go
- go.mod
- go.sum
- vendor/github.com/mattermost/mattermost-server/v6/model/version.go
- vendor/modules.txt
https://mattermost.atlassian.net/browse/DOPS-776
> prepare next release 6.2.4

- commands/version.go
- go.mod
- go.sum
- vendor/github.com/mattermost/mattermost-server/v6/api4/team.go
- vendor/github.com/mattermost/mattermost-server/v6/app/channel.go
- vendor/github.com/mattermost/mattermost-server/v6/model/config.go
- vendor/github.com/mattermost/mattermost-server/v6/model/version.go
- vendor/github.com/mattermost/mattermost-server/v6/services/docextractor/documents.go
- vendor/github.com/mattermost/mattermost-server/v6/store/sqlstore/upgrade.go
- vendor/github.com/mattermost/mattermost-server/v6/web/saml.go
- vendor/modules.txt
> update mmctl to 6.1.3

- commands/version.go
- go.mod
- go.sum
- vendor/modules.txt
> prepare next release 6.1.4

- commands/version.go
- go.mod
- go.sum
- vendor/github.com/mattermost/mattermost-server/v6/model/version.go
- vendor/github.com/mattermost/mattermost-server/v6/store/sqlstore/upgrade.go
- vendor/modules.txt
https://mattermost.atlassian.net/browse/DOPS-776
> update mmctl to 6.3.2

- commands/version.go
- go.mod
- go.sum
- vendor/github.com/mattermost/mattermost-server/v6/app/channel.go
- vendor/github.com/mattermost/mattermost-server/v6/model/config.go
- vendor/github.com/mattermost/mattermost-server/v6/model/version.go
- vendor/github.com/mattermost/mattermost-server/v6/services/docextractor/documents.go
- vendor/github.com/mattermost/mattermost-server/v6/web/saml.go
- vendor/modules.txt
> update mmctl to 6.3.3

- commands/version.go
- go.mod
- go.sum
- vendor/github.com/mattermost/mattermost-server/v6/model/version.go
- vendor/modules.txt
> prepare next release 6.3.4

- go.mod
- go.sum
- vendor/github.com/mattermost/mattermost-server/v5/api4/team.go
- vendor/github.com/mattermost/mattermost-server/v5/model/version.go
- vendor/modules.txt
https://mattermost.atlassian.net/browse/DOPS-776
> update mm to 5.37.7

- commands/version.go
- go.mod
- go.sum
- vendor/github.com/mattermost/mattermost-server/v5/app/channel.go
- vendor/github.com/mattermost/mattermost-server/v5/model/config.go
- vendor/github.com/mattermost/mattermost-server/v5/model/version.go
- vendor/github.com/mattermost/mattermost-server/v5/services/docextractor/documents.go
- vendor/github.com/mattermost/mattermost-server/v5/web/saml.go
- vendor/modules.txt
https://github.com/mattermost/mattermost-helm/pull/302
> update mmctl to 5.37.8

- commands/version.go
- go.mod
- go.sum
- vendor/github.com/mattermost/mattermost-server/v5/model/version.go
- vendor/modules.txt
> prepare next release 5.37.9

- commands/version.go
prepare next release for 6.4.1 
https://mattermost.atlassian.net/browse/DOPS-811
> prepare release 6.4.1

- commands/version.go
> prepare release 6.3.5

- commands/version.go
> prepare release 6.4.2

- commands/version.go
prepare release 6.2.5
https://mattermost.atlassian.net/browse/DOPS-823
> prepare release 6.2.5

- .github/workflows/test.yml
Fix tests mmctl
https://mattermost.atlassian.net/browse/DOPS-838
> Fix broken tests CI for mm-server

- commands/version.go
> Prepare release 6.4.3

- commands/version.go
> prepare release 5.37.10

- commands/version.go
> Prepare release 6.3.6

- commands/version.go
> Prepare release 6.2.6

- commands/version.go
prepare release 6.5.1
https://mattermost.atlassian.net/browse/DOPS-866
> prepare release 6.5.1

- commands/auth.go
> commands/auth: use printer instead of fmt.Println

- commands/user.go
- docs/mmctl_user.rst
- docs/mmctl_user_verify.rst
> commands/user: improve user verify documentation

- commands/auth_utils.go
- commands/auth_utils_test.go
> commands/auth_utils: bugfix on config directory creation

- .github/workflows/test.yml
> Lock CI from /release-6.7

- commands/channel.go
- commands/channel_e2e_test.go
- commands/channel_test.go
Returns multi error instead of printing and returning nil
Fixes https://github.com/mattermost/mattermost-server/issues/21211
> ref: return multi error

- commands/team.go
- commands/team_e2e_test.go
- commands/team_test.go
Refactor - https://github.com/mattermost/mattermost-server/issues/21470
Jira- [MM-47816](https://mattermost.atlassian.net/browse/MM-47816)
> Refact: restoreTeamsCmdF() - Error handling

- commands/channel.go
- commands/channel_e2e_test.go
- commands/channel_test.go
Adds multierror for listChannelsCmdF
Fixes https://github.com/mattermost/mattermost-server/issues/21215
> MM-47344: added multerror result for listChannelsCmdF (#21215)

- commands/plugin_e2e_test.go
I should've update the branches before merging 🤦
> commands/plugin_e2_test: fix an error assertion issue
