mattermost/mmctl

- commands/auth.go
- commands/channel.go
- commands/completion.go
- commands/group.go
- commands/init.go
- commands/license.go
- commands/logs.go
- commands/permissions.go
- commands/plugin.go
- commands/post.go
- commands/root.go
- commands/team.go
- commands/user.go
- commands/websockets.go
This PR renames the `command` variables into `cmd`, and refactors the `Client` initialisation to use the `withClient` decorator.
> With client refactor

- commands/auth.go
- commands/auth_utils.go
Adds an `mmctl auth renew SERVER` command that allows the user to quickly renew their credentials for a given server without the need to input again all the details of a server.
> [MM-19065] Add auth renew command

- commands/permissions_test.go
- commands/user_test.go
Plain values are automatically wrapped with `gomock.Eq`, so we don't need to do it explicitly.
> Remove unnecessary gomock operators

- Makefile
- commands/version.go
Adds a simple version command that shows the `mmctl` compiled version and commit hash.
Jira ticket: https://mattermost.atlassian.net/browse/MM-19890
> Adds version command

- commands/plugin_test.go
Summary:
Add unit tests to "PluginDisableCmd" to use testify
Link:
Fixes https://github.com/mattermost/mattermost-server/issues/13124
> [GH-13124] Add unit tests to "PluginDisableCmd" to use testify

- commands/ldap_test.go
Summary:
Add unit tests to "LdapSyncCmd" to use testify
Link:
Fixes https://github.com/mattermost/mattermost-server/issues/13116
> [GH-13116] Add unit tests to "LdapSyncCmd" to use testify

- commands/command_test.go
Summary:
Add unit tests to "CommandDeleteCmd" to use testify
Link:
Fixes  https://github.com/mattermost/mattermost-server/issues/13113
> [GH-13113] Add unit tests to "CommandDeleteCmd" to use testify

- commands/user_test.go
Summary:
Add unit tests to "ResetUserMfaCmd" to use testify
Link:
Fixes https://github.com/mattermost/mattermost-server/issues/13110
> [GH-13110] Add unit tests to "ResetUserMfaCmd" to use testify

- commands/plugin.go
Fix `mattermost plugin list` to reference plugins as enabled/disabled instead of active/inactive.
https://mattermost.atlassian.net/browse/MM-19915
See also https://github.com/mattermost/mattermost-server/pull/13065
> Fix naming for CLI plugin list command

- commands/plugin_test.go
Summary:
Add unit tests to the "PluginListCmd" mmctl command
Link:
Fixes https://github.com/mattermost/mattermost-server/issues/13161
> [GH-13161] Add unit tests to the "PluginListCmd" mmctl command

- commands/logs_test.go
Fixes: https://github.com/mattermost/mattermost-server/issues/13046
This change includes reading from stdout since the logs command does not use ```printer```.
> GH-13046: Add unit tests to LogsCmd

- commands/group.go
- commands/permissions.go
Small refactor to use `printer` in the `group.go` and `permissions.go` files
> Refactor group and permissions command files to use printer

- commands/license_test.go
Summary:
Add unit tests for `mmctl license remove` command.
Link:
Fixes mattermost/mattermost-server#13158
> Add tests for remove license command

- commands/auth.go
- commands/auth_utils.go
This PR proposes the migration to `fmt.Errorf` from `errors.New` since most of the error messages require formatting. Also, it introduces the all lowercase error messages just like its use in the standard library. (prettier error messages when chaining them.)
This PR aims to discuss these ideas. As a demonstration I implemented these ideas onto `commands/auth.go` and `commands/auth_utils.go`.
> commands/auth: code polish and refactor error messages

- client/client.go
- commands/config.go
- commands/config_test.go
- mocks/client_mock.go
This PR adds two new options (set and reset) to the config option for mmctl
This PR depends on #64 so we need to merge that PR before this one
> Add two new commands for config: set and reset

- commands/post.go
- commands/post_test.go
**Summary**
- Minor refactor on `commands/post.go`.
- Adds tests for the `mmctl post create` command.
Fixes https://github.com/mattermost/mattermost-server/issues/13160
> [MM-20287] Add tests for the post create command

- commands/group_test.go
Add unit tests to the "TeamGroupEnableCmd" mmctl command
https://github.com/mattermost/mattermost-server/issues/13289
> [GH-13289] Add unit tests to the "TeamGroupEnableCmd" mmctl command

- commands/team_test.go
Tests for the remove user from team command have been added to the mmctl tool.
Fixes https://github.com/mattermost/mattermost-server/issues/13284
> GH-13284: Add unit tests to the "RemoveUsersCmd" mmctl command

- commands/team_test.go
Add unit tests to the "DeleteTeamsCmd" mmctl command
Ticket Link: https://mattermost.atlassian.net/browse/MM-21243
Fixes https://github.com/mattermost/mattermost-server/issues/13396
> Add unit tests to the "DeleteTeamsCmd" mmctl command

- README.md
mmctl requires Go 1.13.3 to avoid build error (actually, fails on `go vet` using `shadow`) due to https://github.com/golang/go/issues/34053
> Bump minimum Go version required

- commands/config_test.go
Summary:
Add unit tests to the "PluginListCmd" mmctl command
JIRA: https://mattermost.atlassian.net/browse/MM-20838
closes https://github.com/mattermost/mattermost-server/issues/13286
> MM-20838 Add unit tests to the "ConfigShowCmd" mmctl command

- commands/group_test.go
Add unit tests to the "ListLdapGroupsCmd" mmctl command
Fixes https://github.com/mattermost/mattermost-server/issues/13402
> [GH-13402] Add unit tests to the "ListLdapGroupsCmd" mmctl command

- commands/permissions_test.go
I added 3 unit tests for the removePermissionsCmdF function.
Fixes https://github.com/mattermost/mattermost-server/issues/13404
> GH-13404: Add 3 test cases for removePermissionsCmdF

- commands/config.go
- commands/config_test.go
- commands/plugin_test.go
Added support for map keys with dots in their name. Allows get/set operations on paths like: 
`mmctl config set PluginSettings.PluginStates.com.mattermost.nps.Enable false`
`mmctl config get PluginSettings.PluginStates.com.mattermost.nps.Enable`
`mmctl config get PluginSettings.PluginStates.com.mattermost.nps`
Fixes https://mattermost.atlassian.net/browse/MM-20752
> MM-20752 - MMCTL config get option doesn't allow to pass plugin ids

- .circleci/config.yml
This PR adds a check in lint stage to make sure the docs are updated. The stage fails when the docs are not updated. 
Fixes https://github.com/mattermost/mattermost-server/issues/13625
> [MM-21705] Make sure docs are updated

- Makefile
This PR adds two new mattermost govet checkers:
- tFatal checker [looks for uses of](https://github.com/mattermost/mattermost-govet/blob/master/tFatal/tFatal.go) `t.Fatal` because its use is discouraged
- equalLenAsserts that [checks for users of](https://github.com/mattermost/mattermost-govet/blob/master/equalLenAsserts/equalLenAsserts.go) `assert.Len` and `assert.Equal` and asks for changes providing a better alternative
https://mattermost.atlassian.net/browse/MM-21714
> Added tFatal and equalLenAsserts checkers

- commands/auth.go
Fixes Windows build by enforcing the conversion of `syscall.Stdin`, that is of type `int` in all architectures but in Windows.
> Fixes windows build

- commands/channel.go
- commands/channel_test.go
Summary
Add unit tests to the "RestoreChannelsCmd" mmctl command
Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/13457
Jira Link
https://mattermost.atlassian.net/browse/MM-21388
> [GH-13457] Add unit tests to the "RestoreChannelsCmd" mmctl command

- commands/init.go
Old message was not updated correctly. This PR also makes the command exit with an error instead of printing the help message
> Fixes the error message shown when the strict mode is enabled

- Makefile
Adds `ldflags` to package target to have the commit hash in the version command.
https://mattermost.atlassian.net/browse/MM-22341
> Add ldflags to package target

- commands/permissions_test.go
Summary: 
Add unit tests to the "ShowRoleCmd" mmctl command
Jira: https://mattermost.atlassian.net/browse/MM-20290
Fixes: https://github.com/mattermost/mattermost-server/issues/13403
> [MM-20290] Add unit tests to the "ShowRoleCmd" mmctl command

- commands/command.go
This PR fixes a panic when using `command list` without any arguments.
Fixes https://github.com/mattermost/mmctl/issues/128
> Issue 128: fix panic in 'command list' without args

- commands/channel_test.go
- commands/channelargs.go
- commands/command_test.go
- commands/commandargs.go
- commands/teamargs.go
- commands/user_test.go
- commands/userargs.go
This PR adds a check when querying a user/channel/team with `..`, `/` patterns. Most of the  email providers  does not accept the sequence(`..`) in local-part of an email address. Also more info at [wikipedia article](https://en.wikipedia.org/wiki/Email_address#Local-part)
https://mattermost.atlassian.net/browse/MM-22168
> [MM-22168] commands/user: do not call API if there is a ".." in query

- commands/team.go
- commands/team_test.go
- docs/mmctl_team_rename.rst
Removing the `--name` flag as the API doesn't support to modify the team's name.
https://mattermost.atlassian.net/browse/MM-23036
> [MM-23036] Remove the name flag from the team rename command

- commands/post.go
When upgrading to go 1.14.x a new version of gosimple is fetched (probably by your IDE).  The latest gosimple looks for Sprintf within Println which occured once in mmctl.
```
Running golangci-lint
golangci-lint run ./...
commands/post.go:122:3: S1038: should use fmt.Printf instead of fmt.Println(fmt.Sprintf(...)) (but don't forget the newline) (gosimple)
fmt.Println(fmt.Sprintf("\u001b[31m%s\u001b[0m \u001b[34;1m[%s]\u001b[0m %s", post.Id, username, post.Message))
^
commands/post.go:124:3: S1038: should use fmt.Printf instead of fmt.Println(fmt.Sprintf(...)) (but don't forget the newline) (gosimple)
fmt.Println(fmt.Sprintf("\u001b[34;1m[%s]\u001b[0m %s", username, post.Message))
```
None
> Fix linter error from latest gosimple

- LICENSE.txt
Our code includes the license header, but there was no license file attached to the repository. This PR adds the Apache 2 `LICENSE.txt` file
> Add Apache2 license file

- commands/bot.go
- commands/bot_test.go
- docs/mmctl_bot_disable.rst
Fixes the bot list loop logic that was breaking before processing the resulting users, and the related tests that were duplicating calls to the list endpoint and having other minor issues.
Related to https://github.com/mattermost/mmctl/pull/141
> Fix bot list loop logic and related tests

- commands/channel_test.go
Adds unit tests to the RemoveChannelUsersCmd mmctl command
Fixes https://github.com/mattermost/mattermost-server/issues/13461
> [GH-13461] add unit tests to the RemoveChannelUsersCmd mmctl command

- commands/version.go
Bump `mmctl` version to v5.23 at the release branch
> Bump mmctl version to 5.23.0

- commands/config.go
- commands/config_test.go
- docs/mmctl_config_set.rst
﻿(reflect.Value).Set was being called without checking whether the input
value's type was indeed a slice or not. This would cause a panic in case
when the user is unsure of how to enter an array value to set a config key.
To prevent this, we check for the type and raise an appropriate error
and also add an example to show how to set an array value.
https://mattermost.atlassian.net/browse/MM-24294
> MM-24294: Check the type before assigning a value to a slice

- client/client.go
- commands/channel.go
- mocks/client_mock.go
To allow for deprecation of the [convert channel to private endpoint](https://api.mattermost.com/#tag/channels/paths/~1channels~1{channel_id}~1convert/post) this PR migrates its usage to the [update channel privacy](https://api.mattermost.com/#tag/channels/paths/~1channels~1{channel_id}~1privacy/put) one
Jira ticket: https://mattermost.atlassian.net/browse/MM-25048
> Migrates the make_private command to use the update channel privacy endpoint

- commands/init.go
- commands/init_test.go
This PR checks that when using local mode, the socket file mode and permissions are the expected ones and checks as well that the user that owns the socket is the owner of the process running `mmctl` too.
This is a follow up to the discussion at https://github.com/mattermost/mattermost-server/pull/14333
> Checks that socket file has the right permissions and ownership

- client/client.go
- commands/config.go
- commands/config_test.go
- mocks/client_mock.go
Current implementation uses `/config` endpoint to update server config, but this method shouldn't be used to update single values since it is filling remaining config values with default ones. We should use patch endpoint instead.
https://mattermost.atlassian.net/browse/MM-25067
> [MM-25067] commands/config: use patch method instead of update for set command

- Makefile
- commands/init.go
- commands/init_test.go
- commands/utils_unix.go
- commands/utils_unix_test.go
- commands/utils_windows.go
This PR creates two versions of the `checkValidSocket` func, as windows builds were failing due to `syscall.Stat_t` not being available for the OS.
> Disable syscall usage for windows build

- commands/channel.go
- commands/channel_test.go
- docs/mmctl_channel.rst
- docs/mmctl_channel_restore.rst
- docs/mmctl_channel_unarchive.rst
add unarchive alias to restore channel cmd.
Help will print:
```bash
Restore a previously deleted channel
Channels can be specified by [team]:[channel]. ie. myteam:mychannel or by channel ID.
Usage:
mmctl channel restore [channels] [flags]
Aliases:
restore, unarchive
Examples:
channel restore|unarchive myteam:mychannel
```
https://mattermost.atlassian.net/browse/MM-21501
> [MM-21501] commands/channel: add unarchive alias to restore channel cmd

- client/client.go
- commands/config.go
- commands/config_test.go
- docs/mmctl_config.rst
- docs/mmctl_config_reload.rst
- mocks/client_mock.go
This PR adds config reload command to `mmctl`.
https://mattermost.atlassian.net/browse/MM-19717
> [MM-19717] commands/config: add reload config command

- commands/bot.go
- commands/bot_test.go
This PR fixes a panic in the `bot list` command.  Panic was caused by the code assuming all bots have a valid userId in their ownerId field.  Some bots simply have a descriptive name there.
https://mattermost.atlassian.net/browse/MM-27285
> MM-27285 fix panic in bot list

- commands/bot.go
- commands/channel.go
- commands/init.go
- commands/team.go
Adds a mechanism to forbid some commands from running in local mode and applies it to the commands that were not migrated in time for the local mode phase 2
https://mattermost.atlassian.net/browse/MM-27650
> [MM-27650] Add disable local precheck and disable commands that were not implemented for phase 2

- commands/config.go
- commands/config_test.go
This adds support for setting config values that use integer types with explicit sizes (primarily `int64`). Additionally, it also ensures that provided integer config values fit within the type used.
Fixes #192
https://mattermost.atlassian.net/browse/MM-28421
> Support int64 config values

- commands/user_e2e_test.go
Adds tests for the `mmctl user deactivate` subcommand.
> Add end-2-end tests to user deactivate command

- commands/channel.go
- commands/team.go
This PR removes the local guards for commands that needed endpoints migrated as part of the following tickets:
- [Migrate API handler moveChannel to be compatible with local mode](https://mattermost.atlassian.net/browse/MM-27376)
- [Migrate API handler modifyTeam to be compatible with local mode](https://mattermost.atlassian.net/browse/MM-27377)
- [Migrate API handler restoreTeam to be compatible with local mode](https://mattermost.atlassian.net/browse/MM-27378)
https://mattermost.atlassian.net/browse/MM-29637
> [MM-29637] Remove local guards for migrated commands

- .circleci/config.yml
Update golangci-lint to v1.31.0
Follow up on https://github.com/mattermost/mmctl/pull/242
> Update golangci-lint to v1.31.0

- commands/user_e2e_test.go
Add e2e tests for `userCreateCmdF`.
Fixes https://github.com/mattermost/mattermost-server/issues/15486
JIRA ticket: https://mattermost.atlassian.net/browse/MM-28671
> [MM-28671] Add end-2-ends tests for user create command

- commands/team_e2e_test.go
Adds e2e tests for the `searchTeamCmdF` function.
Fixes https://github.com/mattermost/mattermost-server/issues/15673
JIRA: https://mattermost.atlassian.net/browse/MM-29167
> [MM-29167] Add e2e tests for searchTeamCmdF

- commands/group_test.go
- commands/team_e2e_test.go
This pull request adds end to end tests to the `restoreTeamsCmdF` command, in the `commands/team.go` file.
https://github.com/mattermost/mattermost-server/issues/15677
> [GH-15677] Add e2e tests to the 'restoreTeamsCmdF' mmctl command

- commands/user_e2e_test.go
A change in the error message format of the store is making the e2e tests fail. This PR adapts the checks to the new errors.
> Fix user error messages in tests

- commands/team.go
- commands/team_e2e_test.go
This PR adds tests to `mmctl team modify` command
- https://mattermost.atlassian.net/browse/MM-29170
- Fixes https://github.com/mattermost/mattermost-server/issues/15676
> MM-29170: Add e2e tests to modify teams command

- commands/command_e2e_test.go
**Summary**
Adds e2e tests for archiveCommandCmdF.
**Ticket Link**
Fixes mattermost/mattermost-server#15940
JIRA: https://mattermost.atlassian.net/browse/MM-29562
> [MM-29562]: add e2e tests to archiveCommandCmdF

- commands/roles.go
- commands/roles_test.go
- docs/mmctl.rst
- docs/mmctl_roles.rst
- docs/mmctl_roles_member.rst
- docs/mmctl_roles_system_admin.rst
This PR adds the docs necessary for the CI to pass on the new `mmctl roles` command and subcommands and polishes a bit the way the command filters the roles and prints output instead of returning errors.
https://mattermost.atlassian.net/browse/MM-19060
> Add docs and small modifications to the commands

- Makefile
- commands/mmctl_test.go
Detect if there is a `/enterprise` directory next to `MM_SERVER_PATH` and enable to use `SetupEnterpriseTestHelper`. If there isn't a enterprise directory the suite will simply skip the test case.
https://mattermost.atlassian.net/browse/MM-30093
> [MM-30093] enable enterprise tests for e2e tests

- commands/permissions_role_e2e_test.go
Add `commands/permissions_role` to E2E tests. 
Blocked by #280 
https://mattermost.atlassian.net/browse/MM-30298
> [MM-30298] commands/permissions_role: add e2e test

- commands/user.go
- commands/user_e2e_test.go
- docs/mmctl_user.rst
- docs/mmctl_user_name.rst
- docs/mmctl_user_username.rst
Add new subcommand `name` to the command `user` for changing username of a user account.
Fixes https://github.com/mattermost/mmctl/issues/248
> Add new subcommand name to the command user for changing username of a user account #248

- commands/plugin_e2e_test.go
This PR has e2e test for plugin delete command
Add end to end tests to the "pluginDeleteCmdF" mmctl command
Fixes https://github.com/mattermost/mattermost-server/issues/16076
> [GH-16076] Add end to end tests to the "pluginDeleteCmdF" mmctl command

- commands/group_e2e_test.go
commands/group: add e2e test for ChannelGroupEnableCmd
https://mattermost.atlassian.net/browse/MM-30223
> [MM-30223] commands/group: add e2e test for ChannelGroupEnableCmd

- commands/roles.go
- docs/mmctl.rst
- docs/mmctl_roles.rst
- docs/mmctl_roles_member.rst
- docs/mmctl_roles_system_admin.rst
Adds examples with the new format to the `mmctl roles` subcommands.
```
$ mmctl roles system_admin -h
Make some users system admins.
Usage:
mmctl roles system_admin [users] [flags]
Examples:
$ mmctl roles system_admin john_doe
$ mmctl roles system_admin john_doe jane_doe
```
```
$ mmctl roles member -h
Remove system admin privileges from some users.
Usage:
mmctl roles member [users] [flags]
Examples:
$ mmctl roles member john_doe
$ mmctl roles member john_doe jane_doe
```
> Add examples to roles subcommands

- commands/group_e2e_test.go
Add e2e tests for:
- `teamGroupEnableCmdF`
- `teamGroupDisableCmdF`
- `teamGroupStatusCmdF`
- `teamGroupListCmdF`
https://mattermost.atlassian.net/browse/MM-31414
https://mattermost.atlassian.net/browse/MM-31415
https://mattermost.atlassian.net/browse/MM-31416
https://mattermost.atlassian.net/browse/MM-31417
> commands/group: add e2e tests batch 2

- Makefile
- commands/group_e2e_test.go
- commands/ldap_e2e_test.go
Add e2e tests for:
- `listLdapGroupsCmdF`
- `channelGroupStatusCmdF`
- `channelGroupListCmdF`
- `ldapSyncCmdF`
- `ldapIDMigrateCmdF`
- https://mattermost.atlassian.net/browse/MM-30220
- https://mattermost.atlassian.net/browse/MM-30221
- https://mattermost.atlassian.net/browse/MM-30222
- https://mattermost.atlassian.net/browse/MM-30412
- https://mattermost.atlassian.net/browse/MM-30413
PS: will change base to `master` once we merge https://github.com/mattermost/mmctl/pull/310, alternatively we can merge to `enable_enterprise` branch.
> commands/group, commands/ldap: add e2e tests batch 1

- client/client.go
- commands/saml.go
- commands/saml_test.go
- docs/mmctl.rst
- docs/mmctl_saml.rst
- docs/mmctl_saml_auth-data-reset.rst
- docs/mmctl_saml_authdatareset.rst
- go.mod
- go.sum
- mocks/client_mock.go
- vendor/github.com/mattermost/mattermost-server/v5/api4/saml.go
- vendor/github.com/mattermost/mattermost-server/v5/app/admin.go
- vendor/github.com/mattermost/mattermost-server/v5/app/app.go
- vendor/github.com/mattermost/mattermost-server/v5/app/app_iface.go
- vendor/github.com/mattermost/mattermost-server/v5/app/config.go
- vendor/github.com/mattermost/mattermost-server/v5/app/email.go
- vendor/github.com/mattermost/mattermost-server/v5/app/opentracing/opentracing_layer.go
- vendor/github.com/mattermost/mattermost-server/v5/app/saml.go
- vendor/github.com/mattermost/mattermost-server/v5/app/security_update_check.go
- vendor/github.com/mattermost/mattermost-server/v5/app/server.go
- vendor/github.com/mattermost/mattermost-server/v5/einterfaces/saml.go
- vendor/github.com/mattermost/mattermost-server/v5/model/client4.go
- vendor/github.com/mattermost/mattermost-server/v5/shared/mail/inbucket.go
- vendor/github.com/mattermost/mattermost-server/v5/shared/mail/mail.go
- vendor/github.com/mattermost/mattermost-server/v5/store/sqlstore/user_store.go
- vendor/modules.txt
This PR adds an mmctl command that reset SAML users' AuthData field to their email.
https://mattermost.atlassian.net/browse/MM-32044
https://github.com/mattermost/mattermost-server/pull/17161
> [MM-32044] Reset SAML auth data

- commands/post.go
- printer/printer.go
Routes the prints of the `post list` command through the `printer` to enable JSON formatting.
Fixes #352
> Enable printing the post list in JSON format

- README.md
It threw me off when I didn't see usage section higher.  1/5 on this change.
> DOC: Moved Compile and Developer sections below "usage"

- commands/channel.go
This PR removes the local mode restrictions for the `mmctl` commands that are now enabled after merging https://github.com/mattermost/mattermost-server/pull/17598
https://mattermost.atlassian.net/browse/MM-24864
https://mattermost.atlassian.net/browse/MM-24600
https://mattermost.atlassian.net/browse/MM-27440
> Remove local mode only check from commands after system bot was merged

- commands/channel.go
- commands/channel_test.go
This PR adds a loop for each of the channel fetch functions, so the `channel list` command doesn't hit the max per page limit in the server and effectively fetches all the channels available.
https://mattermost.atlassian.net/browse/MM-37687
> [MM-37687] Add pagination to channel list command

- commands/utils_unix.go
We should avoid erroring for the local mode file ownage if the current user is root.
> bugfix: Do not check local mode socket owner if current user is root

- commands/auth.go
- commands/auth_utils.go
- commands/auth_utils_test.go
- docs/mmctl_auth_login.rst
- docs/mmctl_auth_renew.rst
The `--password` arg may leak a secret into `ps`/`top` output or to shell history. We can encourage users to use a more secure way to supply their secrets. Although existing flags remain, we will mark them as hidden.
```release-note
mmctl will accept --password-file or --access-token-file for login secrets. Please consider updating your scripts accordingly
```
> encourage users to not copy their secrets on shell history

- commands/main_test.go
- commands/mmctl_e2e_test.go
- commands/mmctl_unit_test.go
- commands/utils_unix.go
- magefile.go
Updates mmctl to support go1.17 as described here: https://go.googlesource.com/proposal/+/master/design/draft-gobuild.md
This is currently blocking homebrew here: https://github.com/Homebrew/homebrew-core/pull/83413/
https://github.com/mattermost/mmctl/issues/363
> [Build] Support go 1.17

- client/client.go
- commands/plugin.go
- commands/plugin_e2e_test.go
- commands/plugin_test.go
- docs/mmctl_plugin_add.rst
- mocks/client_mock.go
This allows users to add a plugin with add-and-replace-if-exists semantics when using the `mmctl plugin add`, by specifying the `--force` flag.
This is implemented by calling the `client.UploadPluginForced` function.
Supercedes mattermost/mattermost-server#18081 and resolves #382.
> mmctl plugin add: introduce optional 'force' flag to allow existing plugins to be replaced

- commands/version.go
- go.mod
- go.sum
- vendor/github.com/mattermost/mattermost-server/v5/model/version.go
- vendor/modules.txt
bump mmctl to 5.37.6 in the release-5.37 branch to prepare for the next server release
n/a
> bump mmctl to 5.37.6

- commands/version.go
- go.mod
- go.sum
- vendor/github.com/mattermost/mattermost-server/v6/api4/post.go
- vendor/github.com/mattermost/mattermost-server/v6/api4/user.go
- vendor/github.com/mattermost/mattermost-server/v6/app/app_iface.go
- vendor/github.com/mattermost/mattermost-server/v6/app/opentracing/opentracing_layer.go
- vendor/github.com/mattermost/mattermost-server/v6/app/post.go
- vendor/github.com/mattermost/mattermost-server/v6/app/post_metadata.go
- vendor/github.com/mattermost/mattermost-server/v6/config/logger.go
- vendor/github.com/mattermost/mattermost-server/v6/jobs/resend_invitation_email/worker.go
- vendor/github.com/mattermost/mattermost-server/v6/model/client4.go
- vendor/github.com/mattermost/mattermost-server/v6/store/sqlstore/post_store.go
- vendor/github.com/mattermost/mattermost-server/v6/store/sqlstore/upgrade.go
- vendor/github.com/mattermost/mattermost-server/v6/web/oauth.go
- vendor/github.com/mattermost/mattermost-server/v6/web/saml.go
- vendor/modules.txt
- prepare mmctl to next 6.2 release
> prepare mmctl to next 6.2 release

- commands/version.go
- go.mod
- go.sum
- vendor/github.com/mattermost/mattermost-server/v6/app/file.go
- vendor/github.com/mattermost/mattermost-server/v6/app/post_metadata.go
- vendor/github.com/mattermost/mattermost-server/v6/model/version.go
- vendor/modules.txt
> update mmctl to 6.0.5

- commands/version.go
- go.mod
- go.sum
- vendor/github.com/mattermost/mattermost-server/v6/app/file.go
- vendor/github.com/mattermost/mattermost-server/v6/app/plugin.go
- vendor/github.com/mattermost/mattermost-server/v6/model/version.go
- vendor/modules.txt
> update mmctl to 6.2.2

- commands/version.go
- go.mod
- go.sum
- vendor/github.com/mattermost/mattermost-server/v6/app/file.go
- vendor/github.com/mattermost/mattermost-server/v6/app/post_metadata.go
- vendor/modules.txt
update mmctl to 6.1.2 on release 6.1 branch
> update mmctl to 6.1.2

- commands/config.go
Numeric values coming from plugins' config are mapped to floating point numbers. This made it impossible to update them from `mmctl`.
E.g.
`mmctl --local config set PluginSettings.Plugins.com.mattermost.calls.udpserverport 8443`
would fail with:
```
Error: target value type is not supported
exit status 1
```
PR adds support for such conversion.
https://mattermost.atlassian.net/browse/MM-40604
> [MM-40604] Enable parsing of floating point values from config

- .github/workflows/golangci-lint.yml
Master is broken due to this. Pinning this keeps the code stable and we can make changes slowly.
> Pin golangci to a version

- commands/team.go
- commands/team_e2e_test.go
- commands/team_test.go
We now use the `AllowOpenInvite` field on `Team` to determine if a team is public/invite. This PR ensures this field is set when creating a team.
More context @ https://community-daily.mattermost.com/private-core/pl/kft3wugsnfbqzjuayzrurwnimc
https://mattermost.atlassian.net/browse/MM-41665
> [MM-41665] Set the AllowOpenInvite field to define public/invite only teams

- .github/workflows/test.yml
> Lock CI from /release-6.5

- commands/team_users.go
- docs/mmctl_team_users_add.rst
- docs/mmctl_team_users_remove.rst
Fixes: team users add and remove command example
from : 
``team add myteam user@example.com username``
to 
``team users add myteam user@example.com username``
same for remove
Fixes https://mattermost.atlassian.net/browse/MM-42100
Fixes https://github.com/mattermost/mattermost-server/issues/19637
> [MM-42100] Fixes: team users add and remove command example

- Makefile
- commands/version.go
We get the version number from the recent git tags. So if we need to build this for release, we need to create the tag before releasing.
https://mattermost.atlassian.net/browse/MM-42701
> Makefile: get version from the git tags

- Makefile
- commands/version.go
This PR prepares release-6.3 branch for v6.3.7. 
6.3.6 is released by creating tag. 
Ticket Link
https://mattermost.atlassian.net/browse/DOPS-881
> Prepare release 6.3.7

- Makefile
We cut release-6.6 branch and need to configure `DIST_VER` variable to consider only tags from `v6.6`
> Chore/update dependencies release 6.6

- commands/auth.go
An unsuccessful command should always return a non zero return value, this PR aims to fix this issue.
Fixes #454
> commands/auth: fix 0-return on unsuccessful login attempts

- commands/plugin_marketplace.go
- commands/plugin_marketplace_e2e_test.go
- commands/plugin_marketplace_test.go
- docs/mmctl_plugin_marketplace_install.rst
Since https://github.com/mattermost/mattermost-server/pull/19613, the Marketplace install endpoint always installs the latest version of a given plugin.
This PR updated `mmctl` to take that into account and drops the support for passing a version as part of the command. 
https://mattermost.atlassian.net/browse/MM-42721
> Drop support for installing a plugin with a specific version

- commands/init.go
- commands/init_test.go
- go.mod
- vendor/modules.txt
Fix an issue where we were silently overlooking the error. If we have major version differences or client is ahead of the server we raise a warning. We don't need to raise a warning if the server is ahead of client on the minor version. We need to be backwards compatible.
> commands/init: version check revamped to indicate errors

- commands/import.go
We show the job metadata which captures detail on why
a job has failed. This can be helpful while debugging.
https://mattermost.atlassian.net/browse/MM-38703
```release-note
NONE
```
> MM-38703: Show error detail while printing jobs

- Makefile
We want to automate release cut operation and we need to use different DIST_VER scheme
for release branches. See tickets for details.
Reorder config override include so we can redefine DIST_VER variable at release cut pipeline.
Release cut will create `config.override.mk` file to overwrite that variable.
JIRA: https://mattermost.atlassian.net/browse/DOPS-894
> Reorganize makefile to overwrite DIST_VER variable at release branches

- commands/export.go
- commands/export_e2e_test.go
- docs/mmctl_export_download.rst
We had a resume functionality which would download the file
again from a given offset. But clients would create wrapper
scripts which would auto-retry.
Therefore, we add that functionality in-built and deprecate
the resume flag. The reasoning behind removing the flag is that
if it doesn't succeed within 5 tries, then probably it's better
to attempt to download the file from scratch again sometime later.
https://mattermost.atlassian.net/browse/MM-38701
> MM-38701: Automatically retry on a failed export download

- Makefile
In case there is no Tag available, `DIST_VER` remains unitilized therefore building with an empty `DIST_VER` variable.
For example:
```
Build Linux amd64
env GOOS=linux GOARCH=amd64 go build -trimpath -ldflags '-X github.com/mattermost/mmctl/v6/commands.gitCommit=e58015f66734b77f223592a63d158652e94d5b82 -X github.com/mattermost/mmctl/v6/commands.gitTreeState="clean" -X github.com/mattermost/mmctl/v6/commands.buildDate='2022-05-31T08:20:04Z' -X github.com/mattermost/mmctl/v6/commands.Version=' -mod=vendor
tar cf build/linux_amd64.tar mmctl
md5sum < build/linux_amd64.tar | cut -d ' ' -f 1 > build/linux_amd64.tar.md5.txt
Build Linux arm64
env GOOS=linux GOARCH=arm64 go build -trimpath -ldflags '-X github.com/mattermost/mmctl/v6/commands.gitCommit=e58015f66734b77f223592a63d158652e94d5b82 -X …
```
> [fix] Makefile fallback to using latest semver tag

- Makefile
PR contains changes to check DIST_VER variable with undefined/empty values. When it is empty it will set to latest tag available.
https://mattermost.atlassian.net/browse/CLD-3718
> Makefile sets DIST_VER value empty when there is no tag.

- .golangci.yml
- commands/export.go
- commands/export_e2e_test.go
- commands/export_test.go
- docs/mmctl_export_create.rst
Include attachments by default. Add a new flag to reverse
the logic.
https://mattermost.atlassian.net/browse/MM-38702
> MM-38702: Include attachments by default

- .github/workflows/build.yml
- .github/workflows/golangci-lint.yml
- .gitlab-ci.yml
Mmctl go version is not compatible with Mattermost Server version. PR contains changes to upgrade go version of mmctl.
Related to https://github.com/mattermost/mmctl/issues/547
> Update go version to 1.18 for v7.2

- .github/workflows/build.yml
- .github/workflows/golangci-lint.yml
- .gitlab-ci.yml
Mmctl go version is not compatible with Mattermost Server version. PR contains changes to upgrade go version of mmctl.
Related to https://github.com/mattermost/mmctl/issues/547
> Update go version to 1.18 for v7.1

- printer/printer.go
- printer/printer_test.go
In order to present the progress of the import file validation, we need a way to render lines without a newline. Also due to the progress being rendered multiple times per second (on a half decent machine), this PR adds the possibility to pass pre-parsed templates to the printer to avoid overhead.
[MM-38705](https://mattermost.atlassian.net/browse/MM-38705)
> Add the option to disable newlines and pre-parse templates

- commands/import.go
- commands/importer/types.go
- commands/importer/utils.go
- commands/importer/validate.go
- commands/importer/validators.go
- docs/mmctl_import_validate.rst
- go.mod
- vendor/modules.txt
Adds a validation command for imports. The command uses a copy (currently) of the validators in the `mattermost-server`.
```
mmctl import validate import.zip --team myteam
```
to ignore the attachments when validating, use the `--ignore-attachments` flag.
```
mmctl import validate import.zip --team myteam --ignore-attachments
```
[MM-38705](https://mattermost.atlassian.net/browse/MM-38705)
```release-note
mmctl now allows users to validate import files before uploading them to the server
```
> [MM-38708] Add import validator

- commands/plugin.go
- commands/plugin_e2e_test.go
- commands/plugin_test.go
This pull request adds error handling for pluginInstallUvRLCmdF. The errors are grouped with `multierror.Error` package and returned once the loop is done.
Fixes https://github.com/mattermost/mattermost-server/issues/21223
> [GH-21223] Add error handling for pluginInstallUvRLCmdF

- commands/license.go
- commands/license_test.go
- docs/mmctl_license.rst
- docs/mmctl_license_upload-string.rst
- docs/mmctl_license_upload_string.rst
This command allows uploading a license from a license payload string. We'll need this in Cloud for some upcoming plan change optimizations.
https://mattermost.atlassian.net/browse/MM-46000
> Add a new command to upload a license from a license payload string

- commands/init.go
- commands/init_test.go
Enable `HTTP_PROXY` and `HTTPS_PROXY` environment variables to be used for mmctl.
https://mattermost.atlassian.net/browse/MM-47398
> [MM-47398] add http proxy support

- commands/permission_role_test.go
- commands/permissions_role.go
- commands/permissions_role_e2e_test.go
I added error handling for one error that was not being returned at the end of the function.
fixes https://github.com/mattermost/mattermost-server/issues/21208
Somethings to note:
1. Ive noticed that on E2E tests there is a MM-TXXX, what is that? should I add one of those to my test?
2. I kept the printer error to stderr, this could result in duplicate errors, should it be removed?
> refact: adding error handling for assignUsersCmdF

- commands/roles.go
- commands/roles_test.go
Added multi error handing in rolesSystemAdminCmdF function
Fixes: https://github.com/mattermost/mattermost-server/issues/21477
JIRA: https://mattermost.atlassian.net/browse/MM-47825
> [MM-47825] refactor rolesSystemAdminCmdF function to return an error #21477

- commands/roles.go
- commands/roles_test.go
Return error from rolesMemberCmdF
I applied the same approach with rolesSystemAdminCmd function.
Ticket: [https://github.com/mattermost/mattermost-server/issues/21476](https://github.com/mattermost/mattermost-server/issues/21476)
JIRA Issue: [https://mattermost.atlassian.net/browse/MM-47810](https://mattermost.atlassian.net/browse/MM-47810)
> [MM-47810] Return error from rolesMemberCmdF

- commands/team.go
- commands/team_e2e_test.go
- commands/team_test.go
**Summary**
This PR makes necessary changes for deleteTeamsCmdF function to return an error in case of a failure
**Ticket Link**
Fixes https://github.com/mattermost/mattermost-server/issues/21472
JIRA: https://mattermost.atlassian.net/browse/MM-47814
> [MM-47814] - Refactor deleteTeamsCmdF function error handling

- commands/integrity.go
- commands/integrity_test.go
Returns multi error instead of printing and returning nil
Fixes https://github.com/mattermost/mattermost-server/issues/21209
> [MM-47351] | Add error handling for integrityCmdF function

- commands/export.go
- commands/export_e2e_test.go
- docs/mmctl_export.rst
- docs/mmctl_export_job.rst
- docs/mmctl_export_job_cancel.rst
- docs/mmctl_export_job_list.rst
- docs/mmctl_export_job_show.rst
At the moment, the mattermost client already knows how to cancel a job, but `mmctl` has no subcommands to expose this functionality and cancel an export job.
This PR adds a new subcommand `mmctl export job cancel [export job id]` to cancel an export job. 
This PR is not resolving any open issues in Jira or GitHub. If necessary, I can create a GitHub issue to be able to link the PR to that.
1. Create a new export job
2. Get the export job's ID
3. Execute `mmctl export job cancel <ID>`
First, the export job's state should be `cancel_requested`, then it should switch to `canceled` after some time.
```bash
$ ./mmctl export create --attachments \
| awk -F": " '{print $2}' \
| xargs -n1 -I{} ./mmctl export job cancel "{}"
$ ./mmctl export job list
ID: 59uow53d53f6byk5a4hbwg6y4c
Status: canceled …
```
> Add subcommand for canceling export jobs

- commands/user.go
- commands/user_e2e_test.go
- commands/user_test.go
This PR makes necessary changes for changeUsersActiveStatus function to return an error in case of a failure
Fixes https://github.com/mattermost/mattermost-server/issues/21469
JIRA: https://mattermost.atlassian.net/browse/MM-47817
> MM-47817: Review changeUsersActiveStatus function to return an error in case of a failure

- commands/team_users.go
- commands/team_users_e2e_test.go
- commands/team_users_test.go
Added multi-error handling for teamUsersAddCmdF func.
Issue: mattermost/mattermost-server/issues/21474
Jira: https://mattermost.atlassian.net/browse/MM-47812
> [MM-47812] Refactor addUserToTeam function to return an error

- commands/post.go
Adds error handling for postListCmdF. The errors are grouped with multierror.Error package and returned once the loop is done. 
Fixes https://github.com/mattermost/mattermost-server/issues/21222
> MM-47355: Added multierr for postListCmdF (#21222)

- commands/bot.go
- commands/bot_e2e_test.go
- commands/bot_test.go
Error handling for the `botEnableCmdF` function updated to return an error in case of failure. 
Update includes the use of `multierror.Error` for appending all errors and returning error if one occurs.
Fixes https://github.com/mattermost/mattermost-server/issues/21220
> Issue 21220: improve error handling for botEnableCmdF function

- commands/bot.go
- commands/bot_e2e_test.go
- commands/bot_test.go
Error handling for the `botDisableCmdF` function updated to return an error in case of failure. 
Update includes the use of `multierror.Error` for appending all errors and returning error if one occurs.
Fixes https://github.com/mattermost/mattermost-server/issues/21219
> Issue 21219: improve error handling for botDisableCmdF

- commands/channel.go
- commands/channel_e2e_test.go
- commands/channel_test.go
Returns multi error instead of printing and returning nil
Fixes https://github.com/mattermost/mattermost-server/issues/21214
> ref: return  multi-error from moveChannelCmdF

- commands/channel.go
- commands/plugin_e2e_test.go
- commands/plugin_test.go
This PR is an enhancement on closed tickets https://github.com/mattermost/mattermost-server/issues/21211 and https://github.com/mattermost/mattermost-server/issues/21223 in order to maintain code consistency.
This includes
- Creating error at return
- Updating tests to test against expected error
> Refactor | Creating error at return and update tests

- commands/channel_users.go
- commands/channel_users_test.go
refactor removeAllUsersFromChannel to feedback the error on return instead of just printing
Fixes https://mattermost.atlassian.net/browse/MM-47341
Issue: https://github.com/mattermost/mattermost-server/issues/21218
> refact: removeAllUsersFromChannel to return an error

- commands/command.go
- commands/command_e2e_test.go
- commands/command_test.go
- commands/enterprise.go
Added error handling in `listCommandCmdF` for errors that were only printed and not returned.
Fixes https://github.com/mattermost/mattermost-server/issues/21210
> [GH-21210] refactor(commands): add error handling to listCommandCmdF

- commands/team_users.go
- commands/team_users_test.go
Error handling for the `removeUserFromTeam` function updated to return an error in case of failure.
Update includes the use of `multierror.Error` for appending all errors and returning error if one occurs for the function `teamUsersRemoveCmdF`.
Fixes https://github.com/mattermost/mattermost-server/issues/21475
> MM-47811: improve error handling for removeUserFromTeam function

- Makefile
The installation of binaries using `go get` is not longer supported. The command errors with:
```sh
$ go get -u mattermost-govet
go: go.mod file not found in current directory or any parent directory.
'go get' is no longer supported outside a module.
To build and install a command, use 'go install' with a version,
like 'go install example.com/cmd@latest'
For more information, see https://golang.org/doc/go-get-install-deprecation
or run 'go help get' or 'go help install'.
```
`go install` should be used instead.
None
> Use go install instead of go get 

- .github/workflows/golangci-lint.yml
- commands/websockets.go
I was trying to use the `mmctl websocket` command to monitor the debugbar information and was showing me byte arrays. This PR prints strings instead.
> Showing websockets events as strings instead of as bytes arrays

- .github/workflows/test.yml
- .gitlab-ci.yml
CI was failing to clone `mattermost` as it only tried to use the name of the `mmctl` branch. This patch adds a fix to fallback to the commit previous to mono-repo if we don't have a mirror branch for a PR in `mattermost`.
https://mattermost.atlassian.net/browse/MM-53462
> Fix CI for branches that are not in the mattermost repo
